apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-nodejs-app-config
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  METRICS_PATH: "/metrics"
  
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'simple-nodejs-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['localhost:3000']

  app-settings.json: |
    {
      "timeout": 5000,
      "retries": 3,
      "cacheEnabled": true,
      "cacheTTL": 300,
      "corsSettings": {
        "allowedOrigins": ["*"],
        "allowedMethods": ["GET", "POST", "PUT", "DELETE"]
      }
    }